migratePlaylists = true
migratePlaylistsInteractive = true
migrateStarred = true
mockMigration = false
log = "info"

[source]
host = "http://host"
port = 8080
username = "user"
password = "pass"
legacy = true
version="1.15.0"

[target]
host = "http://host"
port = 8080
username = "user"
password = "pass"
legacy = false
version="1.15.0"

